version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    # Need to add volume for db so it doesnt get erased each boot up / get rid of copy data/ data/ in dockerfile backend
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app:/app/backend
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000
    depends_on:
      - backend
